"""
Format checks for notebook entries. One copy, shared by every notebook.

    uv run --group nb python -m nb.lint <notebook-dir> [chapter ...]

Defaults to every chapter except those a notebook opts out of. Exits non-zero if
anything is flagged, so it can gate a commit.

This is ordinary `nb` code rather than something copied into each notebook,
because it is a CHECKER: it runs at authoring time, reads the notebook and writes
nothing. Nothing it does ends up in the rendered site, so a notebook does not
need it present to render. `_notebook.py` is the opposite -- exec'd into every
page at render time, with its output baked into the published HTML -- which is
why that one is vendored, in `nb/vendored/`, and this one is not.

It sat in `nb/vendor/` beside that file for a while, which is how four modules
that were never vendored came to look as though they were.

**A notebook carries no lint configuration.** Everything that once looked
notebook-specific is either derived or declared where it belongs: the helpers
that cost an aero solve are derived from each chapter's own call graph, a
sibling entry is matched generically, and a chapter opts out with a `_lint-skip`
file whose contents say why. A freshly scaffolded notebook has none of these,
and lints correctly with nothing added.

Thirty-nine rules, each earned by a failure that actually happened. `RULES`
below is the registry -- the numbers, one line each -- and `WHY` beside it is
the failure that earned each one. This docstring used to carry a THIRD copy of
the list, which said "Eighteen rules", stopped at 38, and had disagreed with
`RULES` for months: nothing compared them, because a docstring is not something
a check can hold to anything.

`preflight` compares `RULES` against the list in `system_instruction.md`, which
is the model's copy and is hand-written on purpose -- its wording is tuned for
drafting rather than for diagnosis. That check is what keeps the two in step.

Two details the list cannot carry. A value written as an inline expression counts
as ONE word, so tightening prose is never at odds with computing the numbers in
it. And rules 12 and 15 read the rendered freeze, so they are silent when there
is none -- an unrendered notebook is not thereby clean.
"""

import pathlib
import sys


# =============================================================================
# THE FACADE. `lint.check()` is the whole public surface, and these are the
# names other modules reach for through it -- `config`, `build/freezediff`,
# `tools/verifiers`, `tools/guards`, `tools/interact`, `preflight` and `corpus`
# between them. Re-exported rather than relocated because a phase that moves
# code must not move the names its callers use; each can be pointed at
# `contract` directly, one caller at a time, by whoever is reading that caller.
#
#   contract/contract.py   which rules exist, and the registry
#   contract/shared.py     the parsers, regexes and budget readers
#   contract/rules.py      the 44 checks
#   contract/parse.py      Entry and Chapter, over the parsers
# =============================================================================
from .contract.contract import (  # noqa: E402,F401
    RULES, WHY, _tag, register, run as run_registered, unattributed, unexplained,
)
from .contract.shared import *  # noqa: E402,F403  -- the public parsers
# AND THE THREE `check()` USES ITSELF, so the facade's own dependencies are
# visible rather than arriving through the wildcard.
from .contract.shared import (  # noqa: E402,F401
    ENTRY_FILE, aero_calls_of, chapters_of,
)
# THE PRIVATE ONES, NAMED: a wildcard cannot carry an underscore name, and
# `check()`, `preflight`, `phases/run` and `tools/interact` between them reach
# for these. Sorted and de-duplicated -- the first cut of this list was
# generated by concatenating two sets and listed `_label` three times.
from .contract.shared import (  # noqa: E402,F401
    _bound, _code_only, _computes_nothing, _defaults, _defs_of,
    _departure_targets, _helper_usage, _label, _one_drift,
    _plausible_parent, _rendered_numbers, _visuals_of,
)
from .contract.rules import _notebook_drift  # noqa: E402,F401

# IMPORTED FOR ITS SIDE EFFECT: importing the module runs the `@register`
# decorators, which is what puts the 44 checks in the registry. Last, so every
# name they import from `shared` is bound before they ask for it.
from .contract import rules as _rules  # noqa: E402,F401


def check(root, chapters):
    # `Entry`, not `Path`. It answers everything a Path answers and caches the
    # read and every parse of it, so the rules that call `.read_text()` and the
    # helpers invoked repeatedly over one file now do that work once per file for
    # the whole run. See `contract/parse.Entry`.
    from .contract.parse import Entry
    entries = [Entry(f) for c in chapters
               for f in sorted((root / "chapters" / c).glob("*.qmd"))
               if ENTRY_FILE.match(f.name)]
    # Chapter indexes get the prose checks too. They are prose about the model
    # like any entry, and an unchecked index is how "5.7% thick" survived in
    # one after the model started saying 5.6%.
    pages = entries + [Entry(root / "chapters" / c / "index.qmd") for c in chapters
                       if (root / "chapters" / c / "index.qmd").exists()]

    # Derived per chapter: two chapters model different aircraft with different
    # helpers, and one chapter's `trim` says nothing about another's.
    aero = {c: aero_calls_of(root / "chapters" / c) for c in chapters}

    # EVERY CHECK, AND NOTHING ELSE. This function was 214 lines, of which ten
    # rules were written inline because they had nowhere else to live; the rest
    # was a list of twenty-four dispatch calls saying rule numbers that `RULES`
    # already declared. Both are gone: a check declares its own rule with
    # `@register`, and this assembles the context they ask for by name.
    problems = run_registered(root=root, chapters=chapters, entries=entries,
                              pages=pages, aero=aero)

    # Normalised so every caller sees one shape. `_tag` already produced
    # triples; a check returning `(where, msg)` pairs is padded with `None`.
    return [p if len(p) == 3 else (None, p[0], p[1]) for p in problems]


def main(argv):
    if not argv:
        print(__doc__.strip().split("\n\n")[1].strip())
        return 2
    root = pathlib.Path(argv[0]).resolve()
    if not (root / "chapters").is_dir():
        print(f"  {root} is not a notebook (no chapters/ directory)")
        return 2

    chapters = argv[1:] or chapters_of(root)
    found = check(root, chapters)
    for _rule, where, msg in found:
        label = "" if where is None else (
            _label(where.name) if ENTRY_FILE.match(where.name)
            else f"{where.parent.name}/{where.name}")
        print(f"  {label + ': ' if label else ''}{msg}")
    # Warnings are reported and do not fail. Only rule 17's lower tier uses
    # this: wall clock swings with machine load, so a message about it is worth
    # printing and not worth failing a render over.
    blocking = [p for p in found if "(warning)" not in p[2]]
    warned = len(found) - len(blocking)
    tail = f", {warned} warning(s)" if warned else ""
    print(f"\n{len(blocking)} problem(s){tail} in {', '.join(chapters)}")
    return 1 if blocking else 0


# `python -m nb.lint <notebook>`. The guard belongs with `main`, and briefly did
# not: the split classified it as neither an import nor a function and filed it
# with the parsers, where `__name__` is never `"__main__"`. The command then
# exited silently with status 0 -- a broken entry point that looks like a clean
# notebook.
if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
