{
  "hash": "576e6f5032ba71bfef608e5f8429f4e2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Where does the ballast go, and how much?\"\n---\n\n\nThe neutral point from a straight-line fit of `Cm` against `CL` over α = 0–8°\nat 6 m/s, then the ballast mass that puts the CG a given static margin ahead of\nit. The fit band is used rather than `run_with_stability_derivatives()` because\nthe lift curve is nonlinear at this Reynolds number and point-wise finite\ndifferences on it scatter the neutral point over hundreds of millimetres; the\nband brackets the best-L/D angle. Static margin is not something the plan\nspecifies, so three values are carried rather than one.\n\n::: {#805a8470 .cell execution_count=2}\n``` {.python .cell-code}\nV = 6.0\nalpha = np.linspace(-15, 15, 121)\np = polars(alpha, V=V)\n\nband = (alpha >= 0) & (alpha <= 8)\ndCm_dCL = np.polyfit(np.array(p[\"CL\"])[band], np.array(p[\"Cm\"])[band], 1)[0]\nx_np = x_qc_w - dCm_dCL * c_w\n\nmp0 = mass_properties()\nprint(f\"V = {V:.1f} m/s,  Re_c = {p['Re_c']:.0f}\")\nprint(f\"dCm/dCL over alpha 0-8 deg = {dCm_dCL:+.4f}\")\nprint(f\"neutral point       = {x_np*1e3:6.1f} mm aft of the nose\")\nprint(f\"unballasted CG      = {mp0.x_cg*1e3:6.1f} mm aft of the nose\"\n      f\"  ({mp0.mass*1e3:.2f} g)\")\nprint(f\"static margin as built, no ballast = \"\n      f\"{(x_np - mp0.x_cg)/c_w*100:+.0f} % MAC\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV = 6.0 m/s,  Re_c = 35926\ndCm/dCL over alpha 0-8 deg = -0.4403\nneutral point       =  156.6 mm aft of the nose\nunballasted CG      =  184.5 mm aft of the nose  (12.52 g)\nstatic margin as built, no ballast = -32 % MAC\n```\n:::\n:::\n\n\n::: {#795147aa .cell execution_count=3}\n``` {.python .cell-code}\n# Ballast is a point mass; the CG of structure plus ballast is a weighted mean,\n# so the mass needed at a station follows from the lever ratio.\ndef ballast_for(x_cg_target, x_ballast):\n    return mp0.mass * (mp0.x_cg - x_cg_target) / (x_cg_target - x_ballast)\n\nx_b = np.linspace(0, x_le_w, 200)\nmargins = [0.05, 0.10, 0.15]\nm_b = {SM: ballast_for(x_np - SM * c_w, x_b) for SM in margins}\n\nfor SM in margins:\n    x_cg = x_np - SM * c_w\n    print(f\"SM {SM:4.0%}  (CG {x_cg*1e3:5.1f} mm):  \"\n          f\"{ballast_for(x_cg, 0.0)*1e3:5.2f} g at the nose,  \"\n          f\"{ballast_for(x_cg, x_le_w)*1e3:5.2f} g at the wing leading edge\")\n\nm10 = ballast_for(x_np - 0.10 * c_w, 0.0)\nprint(f\"\\nat 10% MAC with the ballast on the nose: all-up \"\n      f\"{(mp0.mass + m10)*1e3:.2f} g, wing loading \"\n      f\"{(mp0.mass + m10)*9.81/S_w:.2f} N/m^2\")\n\n# What the plan's own ballast would do here, at its best possible station.\ndime = mass_properties(m_ballast=2.268e-3, x_ballast=0.0)\nprint(f\"a dime on the nose: {dime.mass*1e3:.2f} g all-up, CG \"\n      f\"{dime.x_cg*1e3:.1f} mm, static margin {(x_np - dime.x_cg)/c_w*100:+.0f} % MAC\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSM   5%  (CG 152.2 mm):   2.65 g at the nose,   6.87 g at the wing leading edge\nSM  10%  (CG 147.9 mm):   3.10 g at the nose,   8.43 g at the wing leading edge\nSM  15%  (CG 143.5 mm):   3.58 g at the nose,  10.25 g at the wing leading edge\n\nat 10% MAC with the ballast on the nose: all-up 15.62 g, wing loading 5.84 N/m^2\na dime on the nose: 14.78 g all-up, CG 156.2 mm, static margin +0 % MAC\n```\n:::\n:::\n\n\n::: {#cell-fig-ballast .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 4))\n\nfor SM in margins:\n    ax.plot(x_b * 1e3, m_b[SM] * 1e3, label=f\"static margin {SM:.0%} MAC\")\n\nax.axhline(2.268, ls=\"--\", c=\"0.4\", lw=1, label=\"a dime, 2.27 g\")\nax.set_xlabel(\"ballast station [mm aft of the nose]\")\nax.set_ylabel(\"ballast mass [g]\")\nax.set_xlim(0, x_le_w * 1e3)\nax.set_ylim(0, 15)\nax.grid(alpha=0.3)\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Ballast mass needed against the station it is taped to, from the nose back to the wing leading edge, for three static margins at 6 m/s. The dashed line marks the 2.27 g of the dime the plan calls for.](2026-08-27-02-where-does-the-ballast-go-and-how-much_files/figure-html/fig-ballast-output-1.png){#fig-ballast width=1036 height=585}\n:::\n:::\n\n\n**Answer.** On the nose, and about 3 g of it. Unballasted the airframe is\nunstable — 12.52 g of foam puts the CG 184.5 mm aft of the nose against a\nneutral point at 156.6 mm, a static margin of −32% MAC — because a stabilizer\n35% the area of the wing, plus the fin, sit at the end of a 43.8 cm fuselage.\nStation matters more than the mass does: 10% MAC costs 3.10 g at the nose but\n8.43 g at the wing leading edge, where the plan says to tape the dime. A dime\nalone is not enough at this size; 2.27 g on the nose lands the CG at 156.2 mm,\n0.4 mm ahead of the neutral point, which is under half a percent of MAC and\nstable in name only.\n\n",
    "supporting": [
      "2026-08-27-02-where-does-the-ballast-go-and-how-much_files"
    ],
    "filters": [],
    "includes": {}
  }
}