{
  "hash": "eddcfa713db851ae25a5f982b6eed1aa",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Could we use AeroSandbox rather than polyfit to do this calculation?\"\n---\n\n\n`AeroBuildup` already returns a neutral point, so it is read out across the same\n0–8° band at 6 m/s and set against the straight-line fit; then the finite\ndifference behind it is re-run at a range of step sizes, to establish whether\nthe two disagree because of arithmetic or because of the aircraft.\n\n::: {#63f76738 .cell execution_count=2}\n``` {.python .cell-code}\nALPHA = np.linspace(-15, 15, 121)\np = polars(ALPHA, V=6.0)\nCL, Cm = np.array(p[\"CL\"]), np.array(p[\"Cm\"])\nband = np.array([(a >= 0) and (a <= 8) for a in ALPHA])\nslope = np.polyfit(CL[band], Cm[band], 1)[0]\n\n# AeroSandbox computes x_np as xyz_ref[0] - Cma / CLa * c_ref, which is the\n# same formula the fit is put through -- only the slope is sourced differently.\nd = asb.AeroBuildup(\n    airplane=mceagle,\n    op_point=asb.OperatingPoint(velocity=6.0, alpha=np.array([0., 2., 4., 6., 8.])),\n).run_with_stability_derivatives(beta=False, p=False, q=False, r=False)\n\nprint(\"run_with_stability_derivatives()['x_np']:\")\nfor a, x in zip([0., 2., 4., 6., 8.], np.array(d[\"x_np\"])):\n    print(f\"   alpha {a:4.1f} deg   x_np {x*1e3:6.1f} mm\")\nprint(f\"\\nstraight-line fit over the same band: {(x_qc_w - slope*c_w)*1e3:.1f} mm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrun_with_stability_derivatives()['x_np']:\n   alpha  0.0 deg   x_np  170.0 mm\n   alpha  2.0 deg   x_np  158.7 mm\n   alpha  4.0 deg   x_np  147.4 mm\n   alpha  6.0 deg   x_np  161.6 mm\n   alpha  8.0 deg   x_np  197.1 mm\n\nstraight-line fit over the same band: 156.6 mm\n```\n:::\n:::\n\n\n::: {#02ef38ac .cell execution_count=3}\n``` {.python .cell-code}\n# AeroSandbox differences one-sided over a hard-coded 0.001 rad (0.0573 deg).\n# If that step were too small to resolve, shrinking it would move the answer.\ndef slope_at(a0, h_deg):\n    q = polars(np.array([a0 - h_deg, a0 + h_deg]), V=6.0)\n    cl, cm = np.array(q[\"CL\"]), np.array(q[\"Cm\"])\n    return (cm[1] - cm[0]) / (cl[1] - cl[0])\n\nprint(\"central difference about alpha = 4 deg:\")\nfor h in [0.029, 0.1, 0.5, 1.0, 4.0]:\n    s = slope_at(4.0, h)\n    print(f\"   step +/-{h:5.3f} deg   dCm/dCL {s:+.4f}   \"\n          f\"x_np {(x_qc_w - s*c_w)*1e3:6.1f} mm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncentral difference about alpha = 4 deg:\n   step +/-0.029 deg   dCm/dCL -0.3353   x_np  147.4 mm\n   step +/-0.100 deg   dCm/dCL -0.3354   x_np  147.4 mm\n   step +/-0.500 deg   dCm/dCL -0.3380   x_np  147.7 mm\n   step +/-1.000 deg   dCm/dCL -0.3461   x_np  148.4 mm\n   step +/-4.000 deg   dCm/dCL -0.4968   x_np  161.5 mm\n```\n:::\n:::\n\n\n**Answer.** Yes, and it needs no fit: `run_with_stability_derivatives()` returns\n`x_np`, computed as `xyz_ref[0] - Cma / CLa * c_ref` — the same expression the\nfitted slope is put through. Nothing was missing from the library.\n\nThis corrects the reason given in \"Where does the ballast go, and how much?\",\nwhich said the band was used because point-wise finite differences \"scatter the\nneutral point over hundreds of millimetres\". Both halves of that are wrong. The\nhundreds of millimetres came from reading `x_np` across the full −15° to +15°\nsweep, where it diverges past the stall as CLα passes through zero; across the\nband actually fitted, the range is 147.4 to 197.1 mm. And the variation is not\nscatter. Shrinking the difference step at 4° from ±0.5° to ±0.029° leaves the\nslope at −0.3380, −0.3354, −0.3353 — converged, so the arithmetic is sound and the\nneutral point genuinely moves with angle of attack. At this Reynolds number the\nwing and the stabilizer change their share of the lift as incidence changes, and\nthe balance point moves with it.\n\nSo the fit is not suppressing numerical error, as that entry implied; it is\naveraging a real curve into the single slope that \"static margin\" presumes. The\nchoice does not go away either way — `x_np` requires stating the angle it was\ntaken at, and the fit requires stating the band. Both are the same decision, and\neither is defensible as long as it is declared.\n\n",
    "supporting": [
      "2026-08-27-06-could-we-use-aerosandbox-rather-than-polyfit-to-do-this-calculation_files"
    ],
    "filters": [],
    "includes": {}
  }
}