{
  "hash": "fbc62c30258e077e1c11e44ebfce993d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Are we sure the model is correctly using the NACA 0006 airfoil?\"\n---\n\n\nThe section is checked three ways — that the geometry is what it claims, that\nevery surface carries it, and that NeuralFoil returns a symmetric polar from it\n— and then the choice itself is tested by giving each surface the section its\nown chords imply.\n\n::: {#c92430cb .cell execution_count=2}\n``` {.python .cell-code}\naf = asb.Airfoil(\"naca0006\")\nprint(f\"max thickness {af.max_thickness():.4f}, max camber {af.max_camber():.6f}\")\nfor w in mceagle.wings:\n    print(f\"{w.name:11s} sections carry {set(x.airfoil.name for x in w.xsecs)}\")\n\na2 = np.linspace(-4, 4, 9)\nfor Re in [1.6e3, 3.6e4]:                 # the fin tip, and the mean chord\n    r = af.get_aero_from_neuralfoil(alpha=a2, Re=Re)\n    print(f\"Re {Re:7.0f}: CL(0) {np.array(r['CL'])[4]:+.2e}, \"\n          f\"dCL/dalpha {np.polyfit(a2, np.array(r['CL']), 1)[0]:.4f} /deg \"\n          f\"(thin-airfoil 0.1097), confidence \"\n          f\"{float(np.array(r['analysis_confidence'])[0]):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmax thickness 0.0600, max camber 0.000000\nWing        sections carry {'naca0006'}\nStabilizer  sections carry {'naca0006'}\nFin         sections carry {'naca0006'}\nRe    1600: CL(0) +1.11e-16, dCL/dalpha 0.0780 /deg (thin-airfoil 0.1097), confidence 0.94\nRe   36000: CL(0) +1.38e-16, dCL/dalpha 0.0981 /deg (thin-airfoil 0.1097), confidence 0.98\n```\n:::\n:::\n\n\n::: {#9a46ddf8 .cell execution_count=3}\n``` {.python .cell-code}\nfor nm, etas, chords in [(\"wing\", wing_eta, wing_c), (\"stab\", stab_eta, stab_c),\n                         (\"fin\", fin_eta, fin_c)]:\n    tc = t_foam / chords * 100\n    print(f\"{nm:5s} area-weighted t/c \"\n          f\"{np.trapezoid(tc*chords, etas)/np.trapezoid(chords, etas):5.1f}% \"\n          f\"(modelled as 6.0%)\")\n\n# Lift-curve slope against thickness, at the fin's own Reynolds number.\nprint()\nfor nm in [\"naca0006\", \"naca0008\", \"naca0010\", \"naca0013\"]:\n    r = asb.Airfoil(nm).get_aero_from_neuralfoil(alpha=a2, Re=1.56e4)\n    print(f\"  {nm} at Re 15600: dCL/dalpha \"\n          f\"{np.polyfit(a2, np.array(r['CL']), 1)[0]:+.4f} /deg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nwing  area-weighted t/c   5.7% (modelled as 6.0%)\nstab  area-weighted t/c   7.9% (modelled as 6.0%)\nfin   area-weighted t/c  12.8% (modelled as 6.0%)\n\n  naca0006 at Re 15600: dCL/dalpha +0.0807 /deg\n  naca0008 at Re 15600: dCL/dalpha +0.0661 /deg\n  naca0010 at Re 15600: dCL/dalpha +0.0483 /deg\n  naca0013 at Re 15600: dCL/dalpha +0.0175 /deg\n```\n:::\n:::\n\n\n::: {#da43cbc9 .cell execution_count=4}\n``` {.python .cell-code}\ndef swap(af_w, af_h, af_v):\n    \"\"\"The airframe rebuilt with a chosen section on each surface.\"\"\"\n    xs = lambda le, eta, c, af, **kw: asb.WingXSec(xyz_le=le, chord=c,\n                                                   airfoil=af, **kw)\n    return asb.Airplane(\n        name=\"v\", fuselages=mceagle.fuselages, s_ref=S_w, c_ref=c_w, b_ref=b_w,\n        xyz_ref=[x_qc_w, 0, 0],\n        wings=[\n            asb.Wing(name=\"Wing\", symmetric=True, xsecs=[\n                xs([x_le_w, e*b_w/2, e*z_tip], e, c, af_w)\n                for e, c in zip(wing_eta, wing_c)]),\n            asb.Wing(name=\"Stabilizer\", symmetric=True, xsecs=[\n                xs([x_le_h, e*b_h/2, z_h], e, c, af_h, twist=i_h)\n                for e, c in zip(stab_eta, stab_c)]),\n            asb.Wing(name=\"Fin\", xsecs=[\n                xs([x_te_v - c, 0, e*b_v], e, c, af_v)\n                for e, c in zip(fin_eta, fin_c)]),\n        ])\n\n\nALPHA = np.linspace(-15, 15, 121)\nBAND = (ALPHA >= 0) & (ALPHA <= 8)\nmp0 = mass_properties()\n\nfor label, ap in [(\"all 0006, as modelled\", mceagle),\n                  (\"stab 0008, fin 0013\", swap(*map(asb.Airfoil,\n                       [\"naca0006\", \"naca0008\", \"naca0013\"])))]:\n    p = polars(ALPHA, V=6.0, airplane=ap)\n    CL, Cm = np.array(p[\"CL\"]), np.array(p[\"Cm\"])\n    x_np = x_qc_w - np.polyfit(CL[BAND], Cm[BAND], 1)[0] * c_w\n    x_cg = x_np - 0.10 * c_w\n    b = asb.AeroBuildup(airplane=ap, op_point=asb.OperatingPoint(\n        velocity=6.0, alpha=4.0, beta=np.array([-2.0, 2.0]))).run()\n    Cn = np.array(b[\"Cn\"])\n    print(f\"{label:22s} x_np {x_np*1e3:6.1f} mm, ballast \"\n          f\"{mp0.mass*(mp0.x_cg - x_cg)/x_cg*1e3:5.2f} g, Cn_beta \"\n          f\"{(Cn[1]-Cn[0])/4/np.pi*180:+.4f} /rad\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nall 0006, as modelled  x_np  156.6 mm, ballast  3.10 g, Cn_beta +0.0957 /rad\nstab 0008, fin 0013    x_np  150.1 mm, ballast  3.82 g, Cn_beta -0.0085 /rad\n```\n:::\n:::\n\n\n**Answer.** Yes, mechanically. The geometry is a true NACA 0006 — 6.00% thick,\nzero camber — every section of all three surfaces carries it, and NeuralFoil\nreturns CL(0) = 0 to machine precision with a slope near thin-airfoil theory,\nstill at 0.94 confidence down at the fin tip's Re of 1,600.\n\nWhat is not right is the reason recorded for choosing it. Six percent matches\nthe wing's mean chord and nothing else: the same 5 mm foam is 7.9% of the\nstabilizer's chord and 12.8% of the fin's. Matching those makes the model\nworse. NeuralFoil's smooth sections shed lift-curve slope quickly at this scale\n— at the fin's Re of 15,600 it runs 0.081, 0.066, 0.048, 0.018 per degree\nacross 6, 8, 10 and 13% thick — so a 13% fin flips Cn_beta from +0.0957 to\n−0.0085 and the aircraft loses directional stability. A square-cut plate does\nnot behave that way, because its sharp edge fixes separation and reattachment.\nOne thin section on every surface is therefore the right model of a flat plate,\nand being thinner than the tail's true t/c is the point rather than an error.\n\nOne consequence for later work: the Cn_beta above is taken about the model's\nmoment reference at the wing quarter-chord. About the ballasted CG it is\n+0.0485 /rad, a little over half as much, because the fin's arm is shorter from\nthere.\n\n",
    "supporting": [
      "2026-08-27-05-are-we-sure-the-model-is-correctly-using-the-naca-0006-airfoil_files"
    ],
    "filters": [],
    "includes": {}
  }
}