{
  "hash": "9b7856d4ca8ce2c874a8de8465b00bbc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"What assumptions have we made so far, can you rank them by severity?\"\n---\n\n\nEach assumption is swapped for the other readings the plan allows, one at a\ntime with everything else held fixed at 6 m/s, and severity is read as the\nspread it opens in the nose ballast needed for 10% MAC — the conclusion this\nchapter has actually drawn. Two assumptions cannot be tested this way and are\nnamed in the answer instead.\n\n::: {#9baed1b9 .cell execution_count=2}\n``` {.python .cell-code}\nALPHA = np.linspace(-15, 15, 121)\n\n\ndef assess(airplane, x_ref, mp, band=(0, 8), V=6.0):\n    \"\"\"Neutral point, best L/D, and the nose ballast for 10% MAC.\"\"\"\n    p = polars(ALPHA, V=V, airplane=airplane)\n    CL, CD, Cm = np.array(p[\"CL\"]), np.array(p[\"CD\"]), np.array(p[\"Cm\"])\n    k = (ALPHA >= band[0]) & (ALPHA <= band[1])\n    x_np = x_ref - np.polyfit(CL[k], Cm[k], 1)[0] * c_w\n    x_cg = x_np - 0.10 * c_w\n    return x_np, (CL / CD).max(), mp.mass * (mp.x_cg - x_cg) / x_cg\n\n\ndef wing_at(x_le, curved_is_le=False, tip_rise=None):\n    \"\"\"The wing rebuilt at a chosen root LE station, optionally flipped.\"\"\"\n    rise = z_tip if tip_rise is None else tip_rise\n    return asb.Wing(name=\"Wing\", symmetric=True, xsecs=[\n        asb.WingXSec(\n            xyz_le=[x_le + ((wing_c[0] - c) if curved_is_le else 0),\n                    eta * b_w / 2, eta * rise],\n            chord=c, airfoil=airfoil,\n        )\n        for eta, c in zip(wing_eta, wing_c)\n    ])\n\n\ndef with_wing(wing, x_ref):\n    base = build_airplane()\n    return asb.Airplane(\n        name=\"variant\", wings=[wing] + list(base.wings[1:]),\n        fuselages=base.fuselages, s_ref=S_w, c_ref=c_w, b_ref=b_w,\n        xyz_ref=[x_ref, 0, 0],\n    )\n\n\ndef mass_with_wing_at(x_le):\n    \"\"\"The wing carries mass as well as lift, so moving it moves the CG.\"\"\"\n    global x_le_w\n    saved, x_le_w = x_le_w, x_le\n    try:\n        return mass_properties()\n    finally:\n        x_le_w = saved\n```\n:::\n\n\n::: {#34963de6 .cell execution_count=3}\n``` {.python .cell-code}\nmp0 = mass_properties()\nbase = assess(mceagle, x_qc_w, mp0)\n\ncases = {}\n\n# The \"Mount wings here\" bracket runs 119.2 to 166.4 mm aft of the nose -- 47 mm\n# against a 99 mm root chord, so it cannot be marking the chord. The model\n# centres the chord on it; the alternatives pin one end of the chord instead.\ncases[\"wing station on its mount bracket\"] = [\n    assess(with_wing(wing_at(xl), xl + 0.25 * wing_c[0]),\n           xl + 0.25 * wing_c[0], mass_with_wing_at(xl))\n    for xl in [0.1664 - wing_c[0], 0.1192]\n]\n\n# \"A slight negative angle to the plane of the wings\", with no number given.\ncases[\"stabilizer incidence, 0 to -4 deg\"] = [\n    assess(build_airplane(stab_incidence=inc), x_qc_w, mp0)\n    for inc in [0.0, -4.0]\n]\n\n# 5 mm foam on the mean chord is 5.7% thick; the section stands in for a flat\n# plate, and the sheet thickness that picks it is itself assumed.\n_af = airfoil\ncases[\"section standing in for flat foam\"] = []\nfor _name in [\"naca0004\", \"naca0008\"]:\n    airfoil = asb.Airfoil(_name)\n    cases[\"section standing in for flat foam\"].append(\n        assess(build_airplane(), x_qc_w, mp0))\nairfoil = _af\n\n# The wing is traced with one straight edge and one curved; which is the\n# leading edge is a reading of the plan, not a measurement. Flipping it also\n# moves the wing's own centroid, hence the mass offset.\ncases[\"which wing edge is the leading edge\"] = [\n    base,\n    assess(with_wing(wing_at(x_le_w, curved_is_le=True), x_qc_w), x_qc_w,\n           mass_with_wing_at(x_le_w + wing_c[0] - 2 * 0.0450)),\n]\n\n# The neutral point comes from a straight-line fit whose band is a choice.\ncases[\"neutral-point fit band\"] = [\n    assess(mceagle, x_qc_w, mp0, band=b) for b in [(0, 6), (2, 10)]\n]\n\n# Glue is not in the mass build-up at all. It lies where the fuselage lies.\ncases[\"glue, currently not modelled\"] = [\n    (base[0], base[1],\n     (mp0.mass + m) * ((mp0 + asb.MassProperties(mass=m, x_cg=0.1163)).x_cg\n                       - (base[0] - 0.10 * c_w)) / (base[0] - 0.10 * c_w))\n    for m in [0.0, 3.0e-3]\n]\n\ncases[\"operating speed, 4 to 8 m/s\"] = [\n    assess(mceagle, x_qc_w, mp0, V=V) for V in [4.0, 8.0]\n]\n\n# The plan's 2.5 cm tip rise, scaled as an angle or kept as a length.\ncases[\"dihedral, 9.6 or 13.3 deg\"] = [\n    base, assess(with_wing(wing_at(x_le_w, tip_rise=0.025), x_qc_w), x_qc_w, mp0)\n]\n\n_shape = fus_shape\ncases[\"fuselage cross-section exponent\"] = []\nfor fus_shape in [2.0, 10.0]:\n    cases[\"fuselage cross-section exponent\"].append(\n        assess(build_airplane(), x_qc_w, mp0))\nfus_shape = _shape\n\nprint(f\"baseline: x_np {base[0]*1e3:.1f} mm, best L/D {base[1]:.2f}, \"\n      f\"ballast {base[2]*1e3:.2f} g\\n\")\nprint(f\"{'assumption':38s} {'x_np [mm]':>16s} {'L/D':>13s} {'ballast [g]':>14s}\")\norder = sorted(cases, key=lambda k: -abs(cases[k][1][2] - cases[k][0][2]))\nfor k in order:\n    (n0, l0, b0), (n1, l1, b1) = cases[k]\n    print(f\"{k:38s} {n0*1e3:7.1f}{n1*1e3:8.1f} {l0:6.2f}{l1:7.2f}\"\n          f\" {b0*1e3:6.2f}{b1*1e3:7.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbaseline: x_np 156.6 mm, best L/D 6.48, ballast 3.10 g\n\nassumption                                    x_np [mm]           L/D    ballast [g]\nwing station on its mount bracket        135.2   178.0   6.48   6.48   4.59   1.99\nstabilizer incidence, 0 to -4 deg        170.1   151.0   6.54   6.42   1.80   3.71\nneutral-point fit band                   152.5   168.8   6.48   6.48   3.55   1.92\nsection standing in for flat foam        163.2   151.2   6.32   6.38   2.44   3.70\nwhich wing edge is the leading edge      156.6   170.2   6.48   6.54   3.10   2.10\nglue, currently not modelled             156.6   156.6   6.48   6.48   3.10   2.46\noperating speed, 4 to 8 m/s              155.8   160.2   5.87   6.96   3.19   2.73\ndihedral, 9.6 or 13.3 deg                156.6   155.7   6.48   6.51   3.10   3.20\nfuselage cross-section exponent          156.8   156.6   6.60   6.46   3.09   3.10\n```\n:::\n:::\n\n\n::: {#cell-fig-severity .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7.5, 4.2))\n\nlo = np.array([min(cases[k][0][2], cases[k][1][2]) for k in order]) * 1e3\nhi = np.array([max(cases[k][0][2], cases[k][1][2]) for k in order]) * 1e3\ny = np.arange(len(order))[::-1]\n\nax.barh(y, hi - lo, left=lo, height=0.45, color=\"#4C78A8\", zorder=2,\n        label=\"span of the two arms\")\nax.plot(np.full(len(order), base[2] * 1e3), y, \"o\", ms=6, color=\"0.15\",\n        zorder=3, label=\"current model\")\n\nax.set_yticks(y, order)\nax.set_xlabel(\"nose ballast for 10% MAC [g]\")\nax.set_xlim(0, 5)\nax.grid(axis=\"x\", alpha=0.3)\nax.set_axisbelow(True)\nfor side in [\"top\", \"right\", \"left\"]:\n    ax.spines[side].set_visible(False)\nax.legend(loc=\"lower left\", frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Nose ballast required for 10% MAC, as each assumption is swung across the readings the plan allows. Bars span the two arms; the dot marks where the current model sits. Ordered by span.](2026-08-27-04-what-assumptions-have-we-made-so-far-can-you-rank-them-by-severity_files/figure-html/fig-severity-output-1.png){#fig-severity width=1113 height=615}\n:::\n:::\n\n\n**Answer.** No single assumption dominates. Five sit within a factor of about\n2.5 of one another and together set the answer; below them the rest are noise.\n\nLargest is where the wing sits along the fuselage: the plan's mount bracket is\n47 mm long against a 99 mm root chord, so it cannot be marking the chord, and\nthe readings it permits move the neutral point between 135.2 and 178.0 mm — the\nneutral point tracks the wing at about 0.83 mm per mm — and the ballast between\n4.59 and 1.99 g. Then, in order: the stabilizer incidence, which the plan\ndescribes only as \"a slight negative angle\" (1.80–3.71 g); the fit band chosen\nfor the neutral point (1.92–3.55 g); the section standing in for flat foam,\ntogether with the 5 mm thickness that picks it (2.44–3.70 g); and which of the\nwing's two edges is the leading one (2.10–3.10 g). That the fit band — a\nchoice made in the analysis, not in the aircraft — ranks third is worth noting.\nGlue, absent from the mass build-up entirely, only ever helps: it lies forward\nof the structure CG, so 3 g of it cuts the ballast to 2.46 g.\n\nBallast is not the whole story. Best L/D is nearly indifferent to all of the\nabove — it moves 6.32 to 6.60 across every arm — and is set instead by the\nspeed the polar is read at, 5.87 at 4 m/s against 6.96 at 8 m/s. Dihedral and\nthe fuselage cross-section exponent are negligible for anything computed here,\nthough dihedral is a roll-axis device being judged on a pitch-axis result and no\nlateral case has been run.\n\nTwo assumptions cannot be swung inside this model. The first is `AeroBuildup`\nwith NeuralFoil section data standing in for a square-cut foam plate at\nRe 3.6 × 10⁴: the sweep above only substitutes smooth NACA sections, while the\nreal leading edge separates at once, so the best L/D here is optimistic by an\namount this chapter cannot bound. The second is that the airframe is rigid and\ntrue, when the plan's own trimming instructions are to warp the fin.\n\n",
    "supporting": [
      "2026-08-27-04-what-assumptions-have-we-made-so-far-can-you-rank-them-by-severity_files"
    ],
    "filters": [],
    "includes": {}
  }
}